FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-dev \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install PyTorch and other dependencies
RUN pip3 install torch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 --index-url https://download.pytorch.org/whl/cu118

COPY ./requirements_xdit.txt /tmp/requirements_xdit.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements_xdit.txt

# Set working directory
WORKDIR /workspace

# Default command
CMD ["/bin/bash"]